# Generated by Django 5.0.6 on 2024-06-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_indexador_documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
    ]
