# Generated by Django 5.0.6 on 2024-07-01 02:29

import app_indexador_documentos.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indexador_documentos', '0002_rename_documentos_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documentos/', validators=[app_indexador_documentos.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
