# Generated by Django 5.0.6 on 2024-07-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indexador_documentos', '0003_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nome_documento',
            field=models.TextField(max_length=100),
        ),
    ]
